name: Run Python Script

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Python and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openpyxl

    - name: Run Python script
      run: |
        cmd.exe /c "python editable_IDA_copies.py"
